package com.pfe.itsm.tickets.domain;

public enum TicketEventType {
    TICKET_CREE,
    QUALIFIE_PAR_N0,
    SOLUTION_N0_PROPOSEE,
    RESOLU_PAR_N0,
    ESCALADE_VERS_N1,
    PRIS_EN_CHARGE,
    ESCALADE_VERS_N2,
    ESCALADE_VERS_N3,
    INTERVENTION_PLANIFIEE,
    INTERVENTION_DEMARREE,
    INTERVENTION_TERMINEE,
    INTERVENTION_ANNULEE,
    PIECE_CONSOMMEE,
    RESOLU,
    CLOTURE
}
